balance/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calcbook.urls')),
]

calcbook/urls.py
from django.urls import path , include
from . import views

app_name = 'calcbook'

urlpatterns = [
    path('welcome/', views.welcome , name='welcome'),
    path('', views.user_login , name="user_login"),
    path('user_logout/', views.user_logout , name="user_logout"),
    path('add_services/', views.add_services.as_view() , name="add_services"),
    path('add_debit/', views.DebitAddViewCreateView.as_view() , name="add_debit"),
    path('ajax/add_customer/', views.add_customer, name="add_customer"),
    path('ajax/change_name/', views.change_name, name="change_name"),
    path('ajax/change_data/', views.change_data, name="change_data"),
    # path('ajax/change_pending/', views.change_pending, name="change_pending"),
    path('update_services/<int:pk>/update/', views.ServicesUpdateView.as_view(), name="update_services"),
    path('balance/', views.BalanceList.as_view(), name="balance"),
    path('services/', views.ServiceListView.as_view(), name="services"),
    path('daypdf/', views.TodayPdf.as_view(), name="daypdf"),
    path('balpdf/', views.BalancePdf.as_view(), name="balpdf"),
]

templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <title>Login</title>
</head>
<body style="overflow: hidden;">
    <div class="container" id="container">
        <div class="form-container sign-up-container">
        </div>
        <div class="form-container sign-in-container">
            <form action="{% url 'calcbook:user_login' %}" method="POST">
                {%csrf_token%}
                <h1>Sign In</h1>
                <input type="username" name="username" placeholder="Username" />
                <input type="password" name="password" placeholder="Password" />
                <button type="submit" class="si">Sign In</button>
            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                
                <div class="overlay-panel overlay-right">
                    <h1>{{author}}</h1>
                    <p>" {{quotez}} "</p></blockquote>
                </div>
            </div>
        </div>
    </div>
</body>

</html>