balance/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calcbook.urls')),
]

calcbook/models.py
from django.db import models

# Create your models here.
class Customers(models.Model):
    name = models.CharField(max_length = 50)
    phone = models.CharField( max_length=13 , blank=True)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.name

class Services(models.Model):
    service_name = models.CharField(max_length= 50)
    customer_id = models.ForeignKey(Customers , on_delete= models.CASCADE)
    service_charge = models.FloatField()
    profit = models.FloatField()
    isPaid = models.BooleanField()
    paid_amt = models.FloatField()
    service_date = models.DateField()
    bal_paid_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.service_name

class Balance(models.Model):
    service_id = models.ForeignKey(Services , on_delete = models.CASCADE)
    balance_amt = models.FloatField()

    def __str__(self):
        return self.service_id.__str__()

class Amount_debit(models.Model):
    debit_use = models.CharField(max_length= 50)
    debit_amt = models.FloatField()
    debited_date = models.DateField(auto_now=True)

    def __str__(self):
        return self.debit_use

class Total(models.Model):
    total_amt = models.FloatField()
    profit_total = models.FloatField()
    loss_total = models.FloatField()

    def __str__(self):
        return self.total_amt.__str__()

class Service_sites(models.Model):
    site_name = models.CharField(max_length=50)
    site_address = models.CharField(max_length=50)
    site_logo = models.CharField(max_length=100)
    site_desc = models.CharField(max_length=50)

    def __str__(self):
        return self.site_name

templates/add_customer.html
<form action="/add_customer/">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Name:</label>
                <input type="text" name="name" id="name" class="form-control shadow-none">
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Phone:</label>
                <input type="text" name="phone" id="phone" class="form-control shadow-none">
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Email:</label>
                <input type="email" name="email" id="email" class="form-control shadow-none">
            </div>
        </div>
    </div>
    <input type="submit" value="Add Customer" id="add-cust" class="btn btn-primary">
</form>

templates/add_debits.html
{% extends 'base.html' %}
{% block head %}
<title>Add Debits</title>
{% endblock head %}
{% block body_block %}
<form action="" method="POST">
   {% csrf_token %}
   {{form.errors}}
   <div class="row">
      <div class="col-md-6 col-sm-12">
         <div class="form-group">
            <label for="debituse">Debit Use:</label>
            {{form.debit_use}}
         </div>
      </div>
      <div class="col-md-6 col-sm-12">
         <div class="form-group">
            <label for="debitamt">Debit amount:</label>
            {{form.debit_amt}}
         </div>
      </div>
   </div>
   <input type="submit" value="Add Debit" class="btn btn-primary" id="add_debit" />
</form>
<div class="card shadow mb-4 mt-4">
<div class="card-header py-3">
   <div class="table-print" style="display: flex; justify-content: space-between; align-items: center;">
      <h6 class="m-0 font-weight-bold text-primary">Daily Services</h6>
      <button class="btn btn-primary">
         <h6 class="m-0 font-weight-bold ">Print Report</h6>
      </button>
   </div>
</div>
<div class="card-body  border-bottom-primary">
   <div class="table-responsive ">
      <table class="table table-bordered" data-order='[[ 0, "des" ]]' id="dataTable" width="100%" cellspacing="0"
         align="center">
         <thead>
            <tr>
               <th>Debit Use</th>
               <th>Debit Amount</th>
               <th>Date</th>
            </tr>
         </thead>
         <tbody>
            {% for debit in debits %}
            <tr>
               <td>{{debit.debit_use}}</td>
               <td>{{debit.debit_amt}}</td>
               <td>{{debit.debited_date}}</td>
            </tr>
            {% endfor %}
         </tbody>
      </table>
   </div>
</div>
{% endblock body_block %}
{% block javascript %}
<script>
   $(document).ready(function () {
       $('#dataTable').DataTable({
           "ordering": false
       });
   });
</script>
{% endblock javascript %}

templates/add_services.html
{% extends 'base.html' %}


{% block head %}
<title>Add Services</title>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style>
    #checkbox {
        display: flex;
        align-items: center;
        margin: 1rem 0;
        padding-top: 1rem;
    }

    .cust-input {
        display: flex;
        justify-content: space-between;
    }

    #customer {
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }

    .btn-add {
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }

    input[type="checkbox"].ios8-switch {
        position: absolute;
        margin: 8px 0 0 16px;
    }

    input[type="checkbox"].ios8-switch+label {
        position: relative;
        padding: 5px 0 0 50px;
        line-height: 1.0em;
    }

    input[type="checkbox"].ios8-switch+label:before {
        content: "";
        position: absolute;
        display: block;
        left: 0;
        top: 0;
        width: 40px;
        /* x*5 */
        height: 24px;
        /* x*3 */
        border-radius: 16px;
        /* x*2 */
        background: #fff;
        border: 1px solid #d9d9d9;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
    }

    input[type="checkbox"].ios8-switch+label:after {
        content: "";
        position: absolute;
        display: block;
        left: 0px;
        top: 0px;
        width: 24px;
        /* x*3 */
        height: 24px;
        /* x*3 */
        border-radius: 16px;
        /* x*2 */
        background: #fff;
        border: 1px solid #d9d9d9;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
    }

    input[type="checkbox"].ios8-switch+label:hover:after {
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
    }

    input[type="checkbox"].ios8-switch:checked+label:after {
        margin-left: 16px;
    }

    input[type="checkbox"].ios8-switch:checked+label:before {
        background: #55D069;
    }
    .bld
    {
        font-weight: bold;
    }
</style>
{% endblock head %}



{% block body_block %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Service Name:</label>
                {{form.service_name}}
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Customer:</label>
                <div class="cust-input">
                    <input type="text" name="customer" id="customer" class="form-control shadow-none">
                    <span class="input-group-btn">
                        <a href="#" data-toggle="modal" data-target="#CustomerAddModal" style="color: white;"><button
                                class="btn btn-primary btn-add" type="button">+</button></a>
                    </span>
                </div>
                {{form.customer_id}}
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Service Charge:</label>
                {{form.service_charge}}
            </div>
        </div>

        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Profit:</label>
                {{form.profit}}
            </div>
        </div>

        <div class="col-md-6 col-sm-12" id="checkbox">
            <div class="form-group">
                {{form.isPaid}}
                <!-- <label for="servicename">Paid</label> -->
                <label for='checkbox-1'>Paid</label>
            </div>
        </div>

        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Paid Amount:</label>
                {{form.paid_amt}}
            </div>
        </div>
            {{form.service_date}}
        <!-- <div class="col-12">
            <div class="form-group">
                <label for="servicename">Balance Pay Date:</label>
                {{form.bal_paid_date}}
            </div>
        </div> -->
    </div>
    <!-- <input  value="Add Service" class="btn btn-primary" /> -->
    <a href="#" data-toggle="modal" data-target="#promptModal" style="color: white;"><button
        class="btn btn-primary " type="button" id="prompt">Add Service</button></a>
        <input type="submit" value="Add Service" class="btn btn-primary" id="confirmed" style="visibility: hidden;"/>
</form>

<div class="modal fade" id="CustomerAddModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Customer</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                {% include 'add_customer.html' %}
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal" id="cancel-btn">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="promptModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Review Service</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 class="text-center text-danger">Service with Payment done can't be edited</h5>
                <h6>Service <span id="ser-name" class="bld">{Service}</span> is  used by <span id="cust" class="bld">{customer}</span> at a Charge of Rs.<span id="charge" class="bld text-danger">{charge}</span> and has Profit of Rs. <span id="profit" class="bld text-danger">{profit}</span></h6>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal" id="cancel-btn">Go Back and Correct</button>
                <button class="btn btn-primary" type="button"  id="clickbtn">Confirm</button>
            </div>
        </div>
    </div>
</div>

{% endblock body_block %}


{% block javascript %}
<script>
    var dateinp = document.getElementById('id_service_date');
    dateinp.style.display = "none";
    let today = new Date().toLocaleDateString()
    dateinp.value = today;
</script>
<script>
    $('#promptModal #clickbtn').click(function(){
        $('#confirmed').click();
    });
</script>

<script>
    $('#prompt').click(function(){
        var service = document.getElementById("id_service_name").value;
        document.getElementById('ser-name').innerHTML = service;

        var customer = document.getElementById("customer").value;
        document.getElementById('cust').innerHTML = customer;

        var serviceamt = document.getElementById("id_service_charge").value;
        document.getElementById('charge').innerHTML = serviceamt;
        
        var profit = document.getElementById("id_profit").value;
        document.getElementById('profit').innerHTML = profit;
       
    });
</script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function () {
        var projects = [{% for customer in customers %} 
            {
                value: "{{customer.id}}",
                label: "{{customer.name}}",
            },
            {% endfor %}
        ];

        $("#customer").autocomplete({
                minLength: 0,
                source: projects,
                focus: function (event, ui) {
                    $("#customer").val(ui.item.label);
                    return false;
                },
                select: function (event, ui) {
                    $("#customer").val(ui.item.label);
                    $("#id_customer_id").val(ui.item.value);
                    return false;
                }
            })
            .autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                    .append("<div>" + item.label + "<br>" + item.value + "</div>")
                    .appendTo(ul);
            };
    });
</script>
<script>
    document.getElementById("id_paid_amt").value = 0;
    $('#checkbox-1').change(function(){
        if ($('#checkbox-1').is(":checked"))
        {
            var charge = document.getElementById("id_service_charge").value;
            document.getElementById("id_paid_amt").value = charge;
        }
        else
        {
            document.getElementById("id_paid_amt").value = 0;
        }
    })
</script>
<script>
    $('#id_bal_paid_date').datepicker({
        autoclose: true,
        todayHighlight: true
    });
</script>
<script>
    $('#CustomerAddModal #name').focus(function(){
        var randomn = Math.floor(Math.random()*900000) + 100000;
        names = 'user' + randomn;
        document.getElementById("name").value = names;
        $(this).select();
    });

    $("#add-cust").click(function () {
        var name = $('#CustomerAddModal #name').val().trim();
        var phone = $('#CustomerAddModal #phone').val().trim();
        var email = $('#CustomerAddModal #email').val().trim();


        $.ajax({
            url: '/ajax/add_customer/',
            data: {
                'name': name,
                'phone': phone,
                'email': email
            },
            dataType: 'json',
            success: function (data) {
                if (data.successful) {
                    document.getElementsByClassName('modal-body')[0].innerHTML =
                        "<h1>Added Successfully</h1>";
                    document.getElementById('customer').value = data.name;
                    document.getElementById('id_customer_id').value = data.id;
                    document.getElementById('cancel-btn').click();
                }
            }
        });
        event.preventDefault();
    });
</script>
{% endblock javascript %}

templates/balance_list.html
{% extends 'base.html' %}


{% block head %}
<title>Balance List</title>
<style>
    #show
    {
        display: flex;
        justify-content: flex-end;
        align-items: center;
        margin-top: 14px;
    }
</style>
{% endblock %}


{% block body_block %}
<!-- <div class="card shadow mb-4 mt-4">
    <div class="card-body  border-top-primary">
        <form action="" method="POST">
            {% csrf_token %}
            {{form.errors}}
            <div class="row">
               <div class="col-md-4 col-sm-6">
                  <div class="form-group">
                     <label for="debituse">From:</label>
                     {{form.date1}}
                  </div>
               </div>
               <div class="col-md-4 col-sm-6">
                  <div class="form-group">
                     <label for="debitamt">To:</label>
                     {{form.date2}}
                  </div>
               </div>
               <div class="col-md-4 col-sm-12" id="show">
                    <input type="submit" value="Show" class="btn btn-primary btn-block"  />
               </div>
            </div>
        </form>
    </div>
</div> -->

<div class="card shadow mb-4 mt-4">
    <div class="card-header py-3">
        <div class="table-print" style="display: flex; justify-content: space-between; align-items: center;">
            <h6 class="m-0 font-weight-bold text-primary">Balances</h6>
            <button class="btn btn-primary">
                <a href="/balpdf" style="color: white; text-decoration: none;"><h6 class="m-0 font-weight-bold ">Print Report</h6></a>
            </button>
        </div>
    </div>
    <div class="card-body  border-bottom-primary">
        <div class="table-responsive ">
            <table class="table table-bordered" data-order='[[ 0, "des" ]]' id="dataTable" width="100%" cellspacing="0"
                align="center">
                <thead>
                    <tr>
                        <th>Service Name</th>
                        <th>Customer Name</th>
                        <th>Service Charge</th>
                        <th>Service Date</th>
                    </tr>
                </thead>

                <tbody>
                    {% for balance in balances %}
                    <tr>
                        <td>{{balance.service_id.service_name}}</td>
                        <td>{{balance.service_id.customer_id.name}}</td>
                        <td>{{balance.balance_amt}}</td>
                        <td>{{balance.service_id.service_date}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock body_block %}


{% block javascript %}

<script>
    $(document).ready(function () {
        $('#dataTable').DataTable({
            "ordering": false
        });
    });
</script>

<!-- <script>
    $('#date-1').datepicker({
        format: 'yyyy-mm-dd',
        autoclose: true,
        todayHighlight: true
    });

    $('#date-2').datepicker({
        format: 'yyyy-mm-dd',
        autoclose: true,
        todayHighlight: true
    });
</script> -->

    
{% endblock javascript %}
    

templates/balpdf.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ today | date:"d/m/Y" }} Service Details</title>
    <!-- <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@500&display=swap" rel="stylesheet"> -->
    <style type="text/css">
        
        @font-face {
            font-family: Comfortaa , "Comfortaa";
            src: url('https://fonts.googleapis.com/css?family=Comfortaa');
        }

        @page {
            size: A4;
            margin: 1cm;
        }


        body {
            font-family: Comfortaa !important;
        }

        .card-header {
            color: #3A7AB3;
            font-size: 20px;
            text-align: center;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
            color: #000;
            border-left: 1px solid #3A7AB3;
            border-right: 1px solid #3A7AB3;
            border-bottom: 1px solid #3A7AB3;
        }

        .table th
        {
            color:#E64E5F;
            font-weight: bold;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #3A7AB3;
            text-align: left;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #3A7AB3;
        }

        .table tbody+tbody {
            border-top: 2px solid #3A7AB3;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            /* border: 1px solid crimson; */
            /* padding: 5px; */
            text-align: center;
            margin-bottom: 10px;
            padding-top: 8px;
            padding-bottom: 2.5px;
        }

        .list-group h5 {
            font-size: 18px;
            color: white;
        }

        

        .list-group h6 {
            font-size: 15px;
            color: orange;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="card">
            <div class="card-header">
                <h3>Balance Details - {{ today | date:"d/m/Y" }}</h3>
            </div>

            <div class="list-group">
                <table>
                    <tr>
                        <td>
                            <img src="http://api.qrserver.com/v1/create-qr-code/?data=Total_Balance=Rs.{% if total_bal == None  %}0{% else %}{{total_bal}}{% endif %}&color=DDAA51&charset-target=UTF-8&size=100x100" alt="QR error">
                        </td>
                    </tr>
                </table>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>Service Name</th>
                        <th>Customer Name</th>
                        <th>Service Charge</th>
                        <th>Service Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for balance in balances %}
                    <tr>
                        <td>{{ balance.service_id.service_name }}</td>
                        <td>{{ balance.service_id.customer_id.name }}</td>
                        <td>Rs. {{balance.balance_amt}}</td>
                        <td>{{balance.service_id.service_date}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>

</html>

templates/daypdf.html
<h1>
    working !
    {{today}}
</h1>

templates/edit_services.html
{% extends 'base.html' %}


{% block head %}
<title>Update Service</title>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style>
    #checkbox {
        display: flex;
        align-items: center;
        margin: 1rem 0;
        padding-top: 1rem;
    }

    .cust-input {
        display: flex;
        justify-content: space-between;
    }

    #customer {
        border-right: 0;
        border-top-right-radius: 0;
        border-bottom-right-radius: 0;
    }

    .btn-add {
        border-top-left-radius: 0;
        border-bottom-left-radius: 0;
    }

    .loader {
        height: calc(1.5em + .75rem + 2px);
        /* padding: 1px; */
        border: 1px solid #d1d3e2;
        border-left: none;
        border-top-right-radius: 0.35rem;
        border-bottom-right-radius: 0.35rem;
    }

    input[type="checkbox"].ios8-switch {
        position: absolute;
        margin: 8px 0 0 16px;
    }

    input[type="checkbox"].ios8-switch+label {
        position: relative;
        padding: 5px 0 0 50px;
        line-height: 1.0em;
    }

    input[type="checkbox"].ios8-switch+label:before {
        content: "";
        position: absolute;
        display: block;
        left: 0;
        top: 0;
        width: 40px;
        /* x*5 */
        height: 24px;
        /* x*3 */
        border-radius: 16px;
        /* x*2 */
        background: #fff;
        border: 1px solid #d9d9d9;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
    }

    input[type="checkbox"].ios8-switch+label:after {
        content: "";
        position: absolute;
        display: block;
        left: 0px;
        top: 0px;
        width: 24px;
        /* x*3 */
        height: 24px;
        /* x*3 */
        border-radius: 16px;
        /* x*2 */
        background: #fff;
        border: 1px solid #d9d9d9;
        -webkit-transition: all 0.3s;
        transition: all 0.3s;
    }

    input[type="checkbox"].ios8-switch+label:hover:after {
        box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
    }

    input[type="checkbox"].ios8-switch:checked+label:after {
        margin-left: 16px;
    }

    input[type="checkbox"].ios8-switch:checked+label:before {
        background: #55D069;
    }
    .hidden
    {
        display: none;
    }
</style>
{% endblock head %}



{% block body_block %}
<div class="hidden">{{id}}</div>
<form action="" method="POST">
    {% csrf_token %}
    {{form.errors}} 
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Service Name:</label>
                {{form.service_name}}
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Customer:</label>
                <div class="cust-input">
                    <input type="text" name="customer" id="customer" class="form-control shadow-none" value="{{name}}">
                    <span class="input-group-btn">
                        <img class="loader" src="https://www.festivalclaca.cat/imgfv/m/15-155680_camera-icon-white-small-white-camera-icon-transparent.png">
                    </span>
                </div>
                {{form.customer_id}}
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Service Charge:</label>
                {{form.service_charge}}
            </div>
        </div>

        <div class="col-md-6 col-sm-12" id="checkbox">
            <div class="form-group">
                {{form.isPaid}}
                <!-- <label for="servicename">Paid</label> -->
                <label for='checkbox-1'>Paid</label>
            </div>
        </div>

        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Profit:</label>
                {{form.profit}}
            </div>
        </div>
        <!-- <div class="col-md-6 col-sm-12" id="checkbox">
            <div class="form-check">
                {{form.isPaid}}
                <label class="form-check-label" for="isPaid">Paid</label>
            </div>
            
        </div> -->
        {{form.service_date}}
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="servicename">Paid Amount:</label>
                {{form.paid_amt}}
            </div>
        </div>

        {% if isPaid %}
        <h1></h1>
        {% else %}
        <div class="col-12">
            <div class="form-group">
                <label for="servicename">Balance Pay Date:</label>
                {{form.bal_paid_date}}
            </div>
        </div>
        {% endif %}

    </div>
    <a href="#" data-toggle="modal" data-target="#WarningModal" style="color: white;"><button
        class="btn btn-primary " type="button" id="prompt">Update Service</button></a>
    <input type="submit" value="Update Service" class="btn btn-primary" id="update_cust" style="visibility: hidden;"/>
</form>

<div class="modal fade" id="WarningModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Warning</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <h5 class="text-center text-danger">
                    The Payment Status can't be revoked . Are you sure of it?
                </h5>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal" id="cancel-btn">Go Back</button>
                <button class="btn btn-primary" type="button"  id="cnf" data-dismiss="modal">Sure</button>
            </div>
        </div>
    </div>
</div>

{% endblock body_block %}


{% block javascript %}

<script>
    $('#id_service_charge').prop("readonly", true);
    $('#id_profit').prop("readonly", true);
    $('#id_service_name').prop("readonly", true);
    $('#customer').prop("readonly", true);
    if ($('#checkbox-1').is(":checked"))
    {
        $('#checkbox-1').prop("disabled", 'disabled');
    }
</script>
<script>
    // $('#id_bal_paid_date').datepicker({
    //     autoclose: true,
    //     todayHighlight: true
    // });
</script>

<script>
    $("#customer").on('keyup', function () {
        $('.loader').attr('src','https://mir-s3-cdn-cf.behance.net/project_modules/disp/ab79a231234507.564a1d23814ef.gif')
        var name = $('#customer').val()
        var id = $('#id_customer_id').val()

        $.ajax({
            url: '/ajax/change_name/',
            data: {
                'name': name,
                'id': id,
            },
            dataType: 'json',
            success: function (data) {
                if (data.successful) { 
                    $('.loader').attr('src','https://www.festivalclaca.cat/imgfv/m/15-155680_camera-icon-white-small-white-camera-icon-transparent.png') 
                }
            }
        });
        event.preventDefault();
    });
</script>

<script>
    var sercharge = $('#id_service_charge').val()
    let today = new Date().toLocaleDateString()
    $('#id_paid_amt').prop("readonly", true);
    $('#id_bal_paid_date').prop("readonly", true);
    $("#checkbox-1").change(function () {
        if ($('#checkbox-1').is(":checked"))
        {
            document.getElementById("id_paid_amt").value = sercharge;
            document.getElementById("id_bal_paid_date").value = today;
        }
        else
        {
            document.getElementById("id_paid_amt").value = 0 ;
            document.getElementById("id_bal_paid_date").value = '';
        }
    });
</script>

<script>
    var sercharge = $('#id_service_charge').val()
    var profit = $('#id_profit').val()
    var ser_id = $('.hidden').html()
    $("#WarningModal #cnf").click(function () {
        console.log("working")
        if ($('#checkbox-1').is(":checked"))
        {
            console.log("ajax working")
            $.ajax({
                url: '/ajax/change_data/',
                data: 
                {
                    'profit': profit,
                    'ser_id': ser_id,
                    'sercharge': sercharge,
                },
                dataType: 'json',
                success: function (data) 
                {
                    if (data.successful) 
                    { 
                        alert("success")
                    }
                }
            });
            event.preventDefault(); 
        }
    });
</script>
<script>
    $('#WarningModal #cnf').click(function(){
        $('#update_cust').click();
    });
</script>
{% endblock javascript %}